//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.BAIDANGs = new HashSet<BAIDANG>();
        }
    
        public int IDTaiKhoan { get; set; }

        [StringLength(30)]
        [Required(ErrorMessage = "Bạn chưa nhập tên tài khoản")]
        [Display(Name = "Tên Tài khoản")]
        public string TenTaiKhoan { get; set; }

        [Required(ErrorMessage = "Nhập mật khẩu")]
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập họ và tên")]
        [Display(Name = "Họ tên")]
        public string HoTen { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Ngày sinh")]
        [Column(TypeName = "date")]
        [Required(ErrorMessage = "Bạn chưa chọn ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập giới tính")]
        [Display(Name = "Giới tính")]
        public string GioiTinh { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ Email")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ")]
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }

        [StringLength(20)]
        [Required(ErrorMessage = "Bạn chưa nhập số điện thoại")]
        [Display(Name = "Số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        public string SDT { get; set; }

        [Required(ErrorMessage = "Bạn chưa chọn ảnh đại diện")]
        [Display(Name = "Ảnh đại diện")]
        public string AnhDaiDien { get; set; }

        [StringLength(50)]
        public string TrangThaiNguoiDung { get; set; }

        [StringLength(1)]
        public string QuyenHan { get; set; }


    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIDANG> BAIDANGs { get; set; }
    }
}
